# Generated by Django 4.2.2 on 2023-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_useradress_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='address2',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
