# Generated by Django 4.2.2 on 2023-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cartitem_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='order_status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PR', 'Processing'), ('OH', 'On Hold'), ('SH', 'Shipped'), ('DV', 'Delivered'), ('CA', 'Cancelled'), ('RE', 'Returned'), ('RF', 'Refunded')], default=('PE', 'Pending'), max_length=50),
        ),
    ]
