# Generated by Django 4.2.2 on 2023-07-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=255)),
                ('product_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('parent_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_name', models.CharField(max_length=50)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.variation')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU')),
                ('qty_in_stock', models.PositiveIntegerField()),
                ('product_img', models.URLField(blank=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='$')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.productitem')),
                ('variation_option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.variationoption')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.productcategory'),
        ),
    ]
