# Generated by Django 4.2.2 on 2023-07-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Road Frame', 'Road Frame'), ('Mountain Bike Frame', 'Mountain Bike Frame'), ('Hybrid Frame', 'Hybrid Frame'), ('Cyclocross Frame', 'Cyclocross Frame'), ('Touring Frame', 'Touring Frame'), ('Folding Frame', 'Folding Frame'), ('BMX Frame', 'BMX Frame')], max_length=19)),
                ('material', models.CharField(choices=[('Aluminium', 'Aluminium'), ('Steel', 'Steel'), ('Carbon fiber', 'Carbon fiber'), ('Titanium', 'Titanium')], max_length=12)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemId',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Road Bike Saddle', 'Road Bike Saddle'), ('Mountain Bike Saddle', 'Mountain Bike Saddle'), ('Commuter/Comfort Saddle', 'Commuter/Comfort Saddle'), ('Hybrid Bike Saddle', 'Hybrid Bike Saddle'), ('Touring Saddle', 'Touring Saddle'), ('Triathlon/Time Trial Saddle', 'Triathlon/Time Trial Saddle'), ('Gel Saddle', 'Gel Saddle'), ('Leather Saddle', 'Leather Saddle'), ("Women's Saddle", "Women's Saddle"), ("Men's Saddle", "Men's Saddle")], max_length=27)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Clincher', 'Clincher'), ('Tubular', 'Tubular'), ('Tubeless', 'Tubeless')], max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Road Bike Wheel', 'Road Bike Wheel'), ('Mountain Bike Wheel', 'Mountain Bike Wheel'), ('Hybrid Bike Wheel', 'Hybrid Bike Wheel'), ('Cyclocross Bike Wheel', 'Cyclocross Bike Wheel'), ('Touring Bike Wheel', 'Touring Bike Wheel'), ('BMX Bike Wheel', 'BMX Bike Wheel'), ('Fat Bike Wheel', 'Fat Bike Wheel'), ('Gravel Bike Wheel', 'Gravel Bike Wheel'), ('Triathlon Bike Wheel', 'Triathlon Bike Wheel')], max_length=21)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.CharField(editable=False, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.frame')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.seat')),
                ('tires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.tire')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikeshop.wheel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
