# Generated by Django 4.2.2 on 2023-07-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bikeshop.productcategory'),
        ),
    ]
