# Generated by Django 4.2.2 on 2023-07-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0002_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bikeshop.productcategory'),
        ),
    ]
