# Generated by Django 4.2.2 on 2023-07-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0003_alter_productcategory_parent_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='product_variations',
            field=models.ManyToManyField(blank=True, null=True, to='bikeshop.variationoption'),
        ),
    ]
