# Generated by Django 4.2.2 on 2023-07-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0004_productitem_product_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='variation_name',
            new_name='name',
        ),
    ]
