# Generated by Django 4.2.2 on 2023-07-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0005_rename_category_name_productcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
