# Generated by Django 4.2.2 on 2023-07-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0006_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
