# Generated by Django 4.2.2 on 2023-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeshop', '0007_rename_product_name_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='product_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='productitem',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product_variations',
        ),
        migrations.AddField(
            model_name='productitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='bikeshop.variationoption'),
        ),
        migrations.DeleteModel(
            name='ProductConfiguration',
        ),
    ]
